### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by cebe** [asinfotrack/yii2-toolbox#2]
Hi, I'd like to use your `yii2-audittrail` extension, which depends on this package.
Would you mind to tag a release so there is something stable to refer to in composer.json?

**Comment by pasci84** [comment]
Hey cebe!

No problem, it was due for monday anyway! Also for the audittrail itself. Is this ok for you or do you need it before? I could also manage doing it tomorrow.

BTW as you are one of the main yii-devs: how do you usually specify the versioning for extension-projects? For the framework itself its clear, but this size?

Example: v1.2.3 (1: major, 2: breaking and 3: minor / backwards compatible)?

**Comment by cebe** [comment]
No need to hurry, was just wondering.

I suggest to follow semantic versioning for libraries. http://semver.org/

**Comment by pasci84** [comment]
Hey cebe!
I just tagged and released `0.8.0` and also made the audittrail-extension depend on the specific version. OK for you? And BTW: if you feel you could improve the extension...don't hesitate!

**Comment by cebe** [comment]
Awesome, thank you!
